@startuml
!include style.puml
skinparam ArrowFontStyle plain

Participant ":ModelManager" as modelManager MODEL_COLOR
Participant ":PersonList" as personList STORAGE_COLOR
Participant ":SortedList" as sortedList STORAGE_COLOR_T2

[-> modelManager :


modelManager -> personList : getPersonList()
activate personList STORAGE_COLOR

personList -> sortedList : SortedList(filteredPersons, comparator)
activate sortedList STORAGE_COLOR_T2

sortedList --> personList : ObservableList<Person>
deactivate sortedList

personList --> modelManager : ObservableList<Person>
deactivate personList


@enduml
